################################
# Dockerfile: thedcg/ttf-mscorefonts-ubuntu:22.04

# Base
FROM ubuntu:22.04

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true \
  | debconf-set-selections

