################################
# Dockerfile.common

# Maintainer
LABEL org.opencontainers.image.authors="Gravitates Gaudiales <gaudiales@gmail.com>"

# Timezone
ENV TZ=Asia/Tokyo

# Update
RUN date --iso-8601=ns\
 && apt-get update\
 && apt-get -y upgrade\
 && DEBIAN_FRONTEND=noninteractive\
    apt-get -y install\
	curl\
	perl\
	  libencode-perl\
	  libipc-run-perl\
	  libipc-run-safehandles-perl\
	  libjson-perl\
	  liburi-encode-perl\
	  liburi-perl\
	zip\
	unzip\
	dos2unix\
	latexmk\
	\
	tzdata\
	bc\
	make\
	git\
	openssh-client\
	python3-pygments\
	xz-utils\
	tex-common\
	latex-cjk-all\
	texlive-plain-generic\
	texlive-lang-cjk\
	texlive-lang-greek\
	texlive-lang-polish\
	texlive-lang-arabic\
	texlive-lang-other\
	texlive-latex-extra\
	texlive-luatex\
	texlive-pictures\
	texlive-science\
	texlive-fonts-recommended\
	texlive-fonts-extra\
	texlive-metapost\
	texlive-bibtex-extra\
	texlive-publishers\
	fonts-noto-cjk-extra\
	biber\
	asymptote\
	gnuplot\
	poppler-utils\
	qpdf\
	pngcheck\
	qrencode\
	imagemagick\
	libtiff-tools\
	img2pdf\
 && apt-get clean \
 && echo "${TZ}" > /etc/timezone\
 && ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime\
 && dpkg-reconfigure --frontend noninteractive tzdata\
 && mktexlsr \
 && date --iso-8601=ns

# Generate font cache
RUN date --iso-8601=ns\
 && cd /tmp \
 && luaotfload-tool --update --force \
 && for x in $(luaotfload-tool --list=* --fields=fullpath); do \
      /bin/echo "\\relax\\input luaotfload.sty \\font\\x[$x]\\bye" | luatex; \
    done \
 && cd / \
 && date --iso-8601=ns

# End
