################################
# Dockerfile: thedcg/tl-ubuntu:22.04

# ベース
FROM ubuntu:22.04

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true \
  | debconf-set-selections

